name: Mint Token
on:
  workflow_dispatch:
    inputs:
      batch:
        description: 'JSON'
        required: false
        default: '[]'
        type: string
      purpose:
        description: 'Purpose'
        required: false
        default: 'harvest'
        type: string

jobs:
  mint:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello from mint job"
